[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Alex Salman <aalsalma@ucsc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.3.2"
crypto-hash = "0.3.3"
